spring.application.name=CampusRoomStatus

# OAuth
app.google.oauth-client-id=${GOOGLE_CLIENT_ID}
app.google.oauth-client-secret=${GOOGLE_CLIENT_SECRET}
app.google.oauth-refresh-token=${GOOGLE_REFRESH_TOKEN:}

# Google general
app.google.customer=my_customer
app.google.time-zone=Europe/Paris
app.google.max-results-per-page=100

# Décommentez uniquement pour récupérer un refresh token
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=openid,profile,email,https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly,https://www.googleapis.com/auth/calendar.readonly
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token